# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

# from PyQt5.QtWidgets import QGraphicsScene

# scene = QGraphicsScene()

# from PyQt5.QtGui import QPixmap, QGraphicsPixmapItem

# pixmap = QPixmap("chemin/vers/votre/pixelmap.png")  # Chargez votre image
# pixmap_item = QGraphicsPixmapItem(pixmap)  # Créez un objet d'image
# scene.addItem(pixmap_item)  # Ajoutez l'image à la scène

# from PyQt5.QtWidgets import QGraphicsView

# view = QGraphicsView(scene)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 862)
        self.graphicsView = QtWidgets.QGraphicsView(MainWindow)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1111, 861))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
