# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapper.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 862)
        self.labelimage = QtWidgets.QLabel(MainWindow)
        self.labelimage.setGeometry(QtCore.QRect(0, 0, 1111, 881))
        self.labelimage.setText("")
        self.labelimage.setPixmap(QtGui.QPixmap("pixelmap.png"))
        self.labelimage.setScaledContents(True)
        self.labelimage.setObjectName("labelimage")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
