# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton, QMainWindow, QApplication


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelbackground = QtWidgets.QLabel(self.centralwidget)
        self.labelbackground.setGeometry(QtCore.QRect(0, -10, 1041, 641))
        self.labelbackground.setText("")
        self.labelbackground.setPixmap(QtGui.QPixmap("../background.jpg"))
        self.labelbackground.setScaledContents(True)
        self.labelbackground.setObjectName("labelbackground")
        self.logopokemon = QtWidgets.QLabel(self.centralwidget)
        self.logopokemon.setGeometry(QtCore.QRect(200, 70, 581, 201))
        self.logopokemon.setText("")
        self.logopokemon.setPixmap(QtGui.QPixmap("../Pokémon_logo.png"))
        self.logopokemon.setScaledContents(True)
        self.logopokemon.setObjectName("logopokemon")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 460, 191, 61))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0); border: none;")
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Jouer"))


class XXXXWindow (QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(XXXXWindow, self).__init__(parent)
        self.setupUi(self)
# ...
if __name__ == "__main__":
    def run_app():
        app = QApplication(sys.argv)
        mainWin = XXXXWindow()
        mainWin.show()
        app.exec_()
    run_app()