# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Victoire.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton, QMainWindow, QApplication
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Back = QtWidgets.QLabel(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(0, 0, 1001, 751))
        self.Back.setText("")
        self.Back.setPixmap(QtGui.QPixmap("Combat/Outils/Victoire.png"))
        self.Back.setScaledContents(True)
        self.Back.setObjectName("Back")

        self.Pokeball = QtWidgets.QLabel(self.centralwidget)
        self.Pokeball.setGeometry(QtCore.QRect(390, 270, 231, 301))
        self.Pokeball.setText("")
        self.Pokeball.setPixmap(QtGui.QPixmap("Combat/Outils/PokeballOpen.png"))
        self.Pokeball.setScaledContents(False)
        self.Pokeball.setObjectName("Pokeball")
        self.Salameche = QtWidgets.QLabel(self.centralwidget)
        self.Salameche.setGeometry(QtCore.QRect(390, 300, 231, 241))
        self.Salameche.setText("")
        self.Salameche.setPixmap(QtGui.QPixmap("Combat/Outils/Salamèche_face.png"))
        self.Salameche.setScaledContents(True)
        self.Salameche.setObjectName("Salameche")
        self.PokeballButton = QtWidgets.QPushButton(self.centralwidget)
        self.PokeballButton.setGeometry(QtCore.QRect(390, 270, 221, 291))
        self.PokeballButton.setText("")
        self.PokeballButton.setObjectName("PokeballButton")
        self.PartirButton = QtWidgets.QPushButton(self.centralwidget)
        self.PartirButton.setGeometry(QtCore.QRect(260, 680, 481, 31))
        self.PartirButton.setText("")
        self.PartirButton.setObjectName("PartirButton")
        self.Back.raise_()
        self.PokeballButton.raise_()
        self.Pokeball.raise_()
        self.Salameche.raise_()
        self.PartirButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.PokeballButton.setStyleSheet("background-color: rgba(255, 255, 255, 0); border: none;")
        self.PartirButton.setStyleSheet("background-color: rgba(255, 255, 255, 0); border: none;")

        self.Pokeball.enterEvent = self.enter_image
        self.Pokeball.leaveEvent = self.leave_image
        self.Salameche.enterEvent = self.enter_image
        self.Salameche.leaveEvent = self.leave_image

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def enter_image(self, event):
        self.Pokeball.setPixmap(QPixmap("Combat/Outils/PokeballClosed.png"))
        self.Salameche.setPixmap(QPixmap(""))

    def leave_image(self, event):
        self.Pokeball.setPixmap(QPixmap("Combat/Outils/PokeballOpen.png"))
        self.Salameche.setPixmap(QPixmap("Combat/Outils/Salamèche_face.png"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


class XXXXWindow (QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(XXXXWindow, self).__init__(parent)
        self.setupUi(self)
# ...
if __name__ == "__main__":
    def run_app():
        app = QApplication(sys.argv)
        mainWin = XXXXWindow()
        mainWin.show()
        app.exec_()
    run_app()