# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton, QMainWindow, QApplication

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Pokemon2 = QtWidgets.QLabel(self.centralwidget)
        self.Pokemon2.setGeometry(QtCore.QRect(390, 80, 511, 191))
        self.Pokemon2.setText("")
        self.Pokemon2.setPixmap(QtGui.QPixmap("Accueil/Pokémon_logo.png"))
        self.Pokemon2.setScaledContents(True)
        self.Pokemon2.setObjectName("Pokemon2")

        self.jouer = QtWidgets.QPushButton(self.centralwidget)
        self.jouer.setGeometry(QtCore.QRect(915, 375, 131, 51))
        self.jouer.setObjectName("jouer")
        self.regles = QtWidgets.QPushButton(self.centralwidget)
        self.regles.setGeometry(QtCore.QRect(1085, 375, 131, 51))
        self.regles.setObjectName("regles")
        self.Pokemon = QtWidgets.QLabel(self.centralwidget)
        self.Pokemon.setGeometry(QtCore.QRect(800, 125, 511, 191))
        self.Pokemon.setText("")
        self.Pokemon.setPixmap(QtGui.QPixmap("Accueil/Pokémon_logo.png"))
        self.Pokemon.setScaledContents(True)
        self.Pokemon.setObjectName("Pokemon")
        self.labeljouer = QtWidgets.QLabel(self.centralwidget)
        self.labeljouer.setGeometry(QtCore.QRect(915, 325, 131, 151))
        self.labeljouer.setText("")
        self.labeljouer.setPixmap(QtGui.QPixmap("Accueil/1.png"))
        self.labeljouer.setScaledContents(True)
        self.labeljouer.setObjectName("labeljouer")
        self.labelregles = QtWidgets.QLabel(self.centralwidget)
        self.labelregles.setGeometry(QtCore.QRect(1085, 325, 131, 151))
        self.labelregles.setText("")
        self.labelregles.setPixmap(QtGui.QPixmap("Accueil/2.png"))
        self.labelregles.setScaledContents(True)
        self.labelregles.setObjectName("labelregles")
        MainWindow.setCentralWidget(self.centralwidget)

        self.jouer.setStyleSheet("background-color: rgba(255, 255, 255, 0); border: none;")
        self.regles.setStyleSheet("background-color: rgba(255, 255, 255, 0); border: none;")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.jouer.setText(_translate("MainWindow", ""))
        self.regles.setText(_translate("MainWindow", ""))


class XXXXWindow (QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(XXXXWindow, self).__init__(parent)
        self.setupUi(self)
# ...
if __name__ == "__main__":
    def run_app():
        app = QApplication(sys.argv)
        mainWin = XXXXWindow()
        mainWin.show()
        app.exec_()
    run_app()